# frozen_string_literal: true

ruby "2.6.6"
source "https://rubygems.org"

gem "dependabot-omnibus", "~> 0.117.5"
gem 'dependabot-terraform', git: 'https://github.com/plus3it/dependabot-core', branch: "tf012"